require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SectionsController do

  # This should return the minimal set of attributes required to create a valid
  # Section. As you add validations to Section, be sure to
  # update the return value of this method accordingly.
  before(:each) do
    course = Factory.create(:course)
    semester = Factory.create(:semester)
    @attr = { :name => "Spec Section",
              :course_id => course.id,
              :semester_id => semester.id}
  end

  describe "GET index" do
    it "assigns all sections as @sections" do
      section = Section.create! @attr
      get :index
      assigns(:sections).should eq([section])
    end
  end

  describe "GET show" do
    it "assigns the requested section as @section" do
      section = Section.create! @attr
      get :show, :id => section.id
      assigns(:section).should eq(section)
    end
  end

  describe "GET new" do
    it "assigns a new section as @section" do
      get :new
      assigns(:section).should be_a_new(Section)
    end
  end

  describe "GET edit" do
    it "assigns the requested section as @section" do
      section = Section.create! @attr
      get :edit, :id => section.id
      assigns(:section).should eq(section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Section" do
        expect {
          post :create, :section => @attr
        }.to change(Section, :count).by(1)
      end

      it "assigns a newly created section as @section" do
        post :create, :section => @attr
        assigns(:section).should be_a(Section)
        assigns(:section).should be_persisted
      end

      it "redirects to the created section" do
        post :create, :section => @attr
        response.should redirect_to(Section.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved section as @section" do
        # Trigger the behavior that occurs when invalid params are submitted
        Section.any_instance.stub(:save).and_return(false)
        post :create, :section => {}
        assigns(:section).should be_a_new(Section)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Section.any_instance.stub(:save).and_return(false)
        post :create, :section => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested section" do
        section = Section.create! @attr
        # Assuming there are no other sections in the database, this
        # specifies that the Section created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Section.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => section.id, :section => {'these' => 'params'}
      end

      it "assigns the requested section as @section" do
        section = Section.create! @attr
        put :update, :id => section.id, :section => @attr
        assigns(:section).should eq(section)
      end

      it "redirects to the section" do
        section = Section.create! @attr
        put :update, :id => section.id, :section => @attr
        response.should redirect_to(section)
      end
    end

    describe "with invalid params" do
      it "assigns the section as @section" do
        section = Section.create! @attr
        # Trigger the behavior that occurs when invalid params are submitted
        Section.any_instance.stub(:save).and_return(false)
        put :update, :id => section.id, :section => {}
        assigns(:section).should eq(section)
      end

      it "re-renders the 'edit' template" do
        section = Section.create! @attr
        # Trigger the behavior that occurs when invalid params are submitted
        Section.any_instance.stub(:save).and_return(false)
        put :update, :id => section.id, :section => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested section" do
      section = Section.create! @attr
      expect {
        delete :destroy, :id => section.id
      }.to change(Section, :count).by(-1)
    end

    it "redirects to the sections list" do
      section = Section.create! @attr
      delete :destroy, :id => section.id
      response.should redirect_to(sections_url)
    end
  end

end
