require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SemestersController do

  # This should return the minimal set of attributes required to create a valid
  # Semester. As you add validations to Semester, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all semesters as @semesters" do
      semester = Semester.create! valid_attributes
      get :index
      assigns(:semesters).should eq([semester])
    end
  end

  describe "GET show" do
    it "assigns the requested semester as @semester" do
      semester = Semester.create! valid_attributes
      get :show, :id => semester.id
      assigns(:semester).should eq(semester)
    end
  end

  describe "GET new" do
    it "assigns a new semester as @semester" do
      get :new
      assigns(:semester).should be_a_new(Semester)
    end
  end

  describe "GET edit" do
    it "assigns the requested semester as @semester" do
      semester = Semester.create! valid_attributes
      get :edit, :id => semester.id
      assigns(:semester).should eq(semester)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Semester" do
        expect {
          post :create, :semester => valid_attributes
        }.to change(Semester, :count).by(1)
      end

      it "assigns a newly created semester as @semester" do
        post :create, :semester => valid_attributes
        assigns(:semester).should be_a(Semester)
        assigns(:semester).should be_persisted
      end

      it "redirects to the created semester" do
        post :create, :semester => valid_attributes
        response.should redirect_to(Semester.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved semester as @semester" do
        # Trigger the behavior that occurs when invalid params are submitted
        Semester.any_instance.stub(:save).and_return(false)
        post :create, :semester => {}
        assigns(:semester).should be_a_new(Semester)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Semester.any_instance.stub(:save).and_return(false)
        post :create, :semester => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested semester" do
        semester = Semester.create! valid_attributes
        # Assuming there are no other semesters in the database, this
        # specifies that the Semester created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Semester.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => semester.id, :semester => {'these' => 'params'}
      end

      it "assigns the requested semester as @semester" do
        semester = Semester.create! valid_attributes
        put :update, :id => semester.id, :semester => valid_attributes
        assigns(:semester).should eq(semester)
      end

      it "redirects to the semester" do
        semester = Semester.create! valid_attributes
        put :update, :id => semester.id, :semester => valid_attributes
        response.should redirect_to(semester)
      end
    end

    describe "with invalid params" do
      it "assigns the semester as @semester" do
        semester = Semester.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Semester.any_instance.stub(:save).and_return(false)
        put :update, :id => semester.id, :semester => {}
        assigns(:semester).should eq(semester)
      end

      it "re-renders the 'edit' template" do
        semester = Semester.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Semester.any_instance.stub(:save).and_return(false)
        put :update, :id => semester.id, :semester => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested semester" do
      semester = Semester.create! valid_attributes
      expect {
        delete :destroy, :id => semester.id
      }.to change(Semester, :count).by(-1)
    end

    it "redirects to the semesters list" do
      semester = Semester.create! valid_attributes
      delete :destroy, :id => semester.id
      response.should redirect_to(semesters_url)
    end
  end

end
